title: Could Be Architecture
author:
  name: Could Be Architecture
  email: 'joseph@couldbearchitecture.com'
metadata:
    description: 'Could Be Architecture is a multi-disciplinary architecture studio based out of Chicago'

