title: 'Could Be Architecture'
default_lang: en
author:
  name: 'Could Be Architecture'
  email: joseph@couldbearchitecture.com
taxonomies:
  - category
  - tag
  - size
metadata:
  description: 'Could Be Architecture is a multi-disciplinary architecture studio based out of Chicago'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
